version: '3.8'

services:
  backend:
    build:
      context: ../backend
    volumes:
      - ../backend/app:/app

  frontend:
    build:
      context: ../frontend
    volumes:
      - ../frontend/src:/app/src

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
